export const ErrorCodes = {

  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND: 'USER_NOT_FOUND',


  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EXTERNAL_AUTH_ERROR: 'EXTERNAL_AUTH_ERROR',
  FORBIDDEN: 'FORBIDDEN',


  ROLE_NOT_FOUND: 'ROLE_NOT_FOUND',


  CONFLICT: 'CONFLICT',
  NOT_FOUND: 'NOT_FOUND',

  KEYCLOAK_ERROR: 'KEYCLOAK_ERROR',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  //APPOINTMENT

  APPOINTMENT_ALREADY_EXIST: 'APPOINTMENT_ALREADY_EXIST',
  SCHEDULE_NOT_FOUND: 'SCHEDULE_NOT_FOUND',
  SCHEDULE_NOT_AVAILABLE: 'SCHEDULE_NOT_AVAILABLE',
  DOCTOR_NOT_FOUND: 'DOCTOR_NOT_FOUND',
  INVALID_INPUT: 'INVALID_INPUT',
  INVALID_INTERVAL: 'INVALID_INTERVAL',
  APPOINTMENT_NOT_FOUND: 'APPOINTMENT_NOT_FOUND'
} as const;